/* AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY. */
/* Generated by scripts/generate-admin-manual-retrieval-corpus.mjs */

export type AdminManualRetrievalChunk = {
  id: string;
  path: string;
  title: string;
  text: string;
};

export const retrievalCorpus: AdminManualRetrievalChunk[] = [
  {
    "id": "README.md#1",
    "path": "README.md",
    "title": "README.md",
    "text": "Public marketing website and owner operations dashboard for ExtraSure Pest Control in Syracuse, NY, built with Next.js App Router and optimized for lead generation, dispatch visibility, and payment operations."
  },
  {
    "id": "README.md#2",
    "path": "README.md",
    "title": "README.md",
    "text": "For Prisma and Stripe local development, mirror the needed values into `.env` as well because Prisma CLI reads from `.env`."
  },
  {
    "id": "README.md#3",
    "path": "README.md",
    "title": "README.md",
    "text": "- `SITE_URL` or `NEXT_PUBLIC_SITE_URL` - `STRIPE_PUBLISHABLE_KEY` - `STRIPE_SECRET_KEY` - `STRIPE_WEBHOOK_SECRET` - `BILLING_ACCESS_SECRET` (required in production for customer payment links)"
  },
  {
    "id": "README.md#4",
    "path": "README.md",
    "title": "README.md",
    "text": "- Pay an open invoice from `/admin/payments` - Generate and copy a customer payment link from `/admin/payments` - Pay through the customer page at `/pay` - Start autopay for a recurring invoice from `/admin/payments` - Pause, resume, and cancel-at-period-end for recurring subscriptions from `/admin/payments` - Pause, resume, and cancel-at-period-end from the customer token page `/pay/[token]` - Open the Stripe billing portal from `/admin/payments` - Refund a successful payment from `/admin/payments` - Reconcile and replay webhook-backed invoice updates from `/admin/payments`"
  },
  {
    "id": "README.md#5",
    "path": "README.md",
    "title": "README.md",
    "text": "Webhook processing is the source of truth for payment success/failure and subscription updates. Public payment routes include fixed-window rate limiting and return user-facing retry messaging when throttled."
  },
  {
    "id": "README.md#6",
    "path": "README.md",
    "title": "README.md",
    "text": "1. At least one successful route returns `200`. 2. If all configured routes fail, API returns `502`. 3. If no routes are configured, the API still returns `200` and logs the lead server-side for local testing."
  },
  {
    "id": "vercel.json#1",
    "path": "vercel.json",
    "title": "vercel.json",
    "text": "{ \"$schema\": \"https://openapi.vercel.sh/vercel.json\", \"buildCommand\": \"npm run build\", \"crons\": [ { \"path\": \"/api/internal/triage-retention\", \"schedule\": \"0 4 * * *\" } ] }"
  },
  {
    "id": "package.json#1",
    "path": "package.json",
    "title": "package.json",
    "text": "{ \"name\": \"extrasure\", \"version\": \"0.1.0\", \"private\": true, \"scripts\": { \"dev\": \"prisma generate --schema prisma/schema.prisma && next dev\", \"manual:refresh-corpus\": \"node scripts/generate-admin-manual-retrieval-corpus.mjs\", \"build\": \"npm run manual:refresh-corpus && node scripts/prisma-prepare.mjs && next build\", \"build:vercel\": \"npm run manual:refresh-corpus && node scripts/prisma-prepare.mjs && next build\", \"start\": \"next start\", \"lint\": \"eslint\", \"test\": \"jest --runInBand\", \"db:generate\": \"node scripts/prisma-prepare.mjs\", \"db:generate:postgres\": \"prisma generate --schema prisma/schema.postgresql.prisma\", \"db:push\": \"prisma db push\", \"db:push:postgres\": \"prisma db push --schema prisma/schema.postgresql.prisma\", \"db:seed\": \"prisma db seed\", \"db:dedupe:technicians\": \"node --env-file=.env scripts/dedupe-technicians.mjs\", \"db:purge:triage\": \"node --env-file=.env scripts/purge-triage-retention.mjs\", \"db:seed:prod\": \"prisma generate --schema prisma/schema.postgresql.prisma && tsx prisma/"
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#1",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Reframes the ExtraSure experience around a warm, premium, minimalist visual language. - Preserves the existing application structure and product behavior while replacing the shared design system."
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#2",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Refined neutral palette with understated contrast. - More elegant typography pairing and calmer spacing rhythm. - Premium treatment across homepage, CTA, account shell, and admin shell."
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#3",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Rebuilds the site around a dark, layered glassmorphism direction. - Keeps behavior unchanged while shifting the brand into a more cinematic and technical visual mode."
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#4",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Frosted panel system with blur and translucency. - High-contrast dark chrome across public and dashboard surfaces. - Shared shell surfaces updated to feel more immersive and premium."
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#5",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Pushes the site into a more futuristic, neon-forward visual identity. - Maintains all product flows while dramatically increasing visual energy."
  },
  {
    "id": "docs/THEME-REDESIGN-PR-OUTLINES.md#6",
    "path": "docs/THEME-REDESIGN-PR-OUTLINES.md",
    "title": "THEME-REDESIGN-PR-OUTLINES.md",
    "text": "- Saturated neon accents and darker gradient fields. - Sharper, more aggressive visual hierarchy. - Matching treatment across homepage, CTA, account, and admin surfaces."
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#1",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "Transforms the account area into an intelligent home protection operating system while preserving existing account routes, backend integrations, data models, and user actions."
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#2",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "- `src/lib/account-home-intelligence.ts` - `src/lib/account-home-intelligence.test.ts` - `src/components/account/account-home-dashboard.tsx` - `src/components/account/account-home-timeline.tsx` - `src/components/account/account-home-timeline.test.ts` - `src/components/account/account-home-timeline.interaction.test.tsx`"
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#3",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "- `src/app/account/page.tsx` - `src/app/account/services/page.tsx` - `src/app/account/activity/page.tsx` - `src/app/account/billing/page.tsx` - `src/app/account/invoices/page.tsx` - `src/app/account/profile/page.tsx` - `src/app/account/notes/page.tsx` - `src/app/account/loading.tsx`"
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#4",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "- `src/components/account/account-shell.tsx` - `src/components/account/account-ai-assistant-card.tsx` - `src/app/globals.css`"
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#5",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "- `jest.config.cjs` (now includes `.test.tsx` matching) - `package.json` and `package-lock.json` (testing-library/jsdom dependencies)"
  },
  {
    "id": "docs/ACCOUNT-OS-ROLLOUT-PR.md#6",
    "path": "docs/ACCOUNT-OS-ROLLOUT-PR.md",
    "title": "ACCOUNT-OS-ROLLOUT-PR.md",
    "text": "- `npm run lint -- src/app/account/page.tsx src/app/account/services/page.tsx src/app/account/activity/page.tsx src/app/account/billing/page.tsx src/app/account/invoices/page.tsx src/app/account/profile/page.tsx src/app/account/notes/page.tsx src/app/account/loading.tsx src/components/account/account-shell.tsx src/components/account/account-home-dashboard.tsx src/components/account/account-home-timeline.tsx src/components/account/account-home-timeline.test.ts src/components/account/account-home-timeline.interaction.test.tsx src/components/account/account-ai-assistant-card.tsx src/lib/account-home-intelligence.ts src/lib/account-home-intelligence.test.ts jest.config.cjs` - Result: pass"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#1",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "### AI Chat Fallback Behavior - Matches user input against internal FAQs and service descriptions - Returns canned responses based on keyword patterns - **NOT using actual AI language models**"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#2",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "### AI Triage Fallback Behavior - Uses simple keyword detection patterns: - \"dropping\", \"mouse\", \"rat\" → \"Rodent activity\" (confidence: 0.62) - \"termite\", \"wood damage\" → \"Possible termite activity\" (confidence: 0.62) - \"bed bug\", \"bites\" → \"Possible bed bug activity\" (confidence: 0.62) - Everything else → \"General pest activity\" (confidence: 0.48) - **NOT using actual AI models**"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#3",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "1. Go to https://platform.openai.com/api-keys 2. Sign up or log in to your OpenAI account 3. Click \"Create new secret key\" 4. Copy the key (it starts with `sk-`) 5. **Important**: Keep this key secure and never commit it to git!"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#4",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "```bash # Replace YOUR_OPENAI_API_KEY_HERE with your actual key OPENAI_API_KEY=sk-your-actual-key-here AI_CHAT_MODEL=gpt-4o-mini AI_TRIAGE_MODEL=gpt-4o-mini ```"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#5",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "```bash # Replace YOUR_OPENAI_API_KEY_HERE with your actual key OPENAI_API_KEY=sk-your-actual-key-here AI_CHAT_MODEL=gpt-4o-mini AI_TRIAGE_MODEL=gpt-4o-mini ```"
  },
  {
    "id": "docs/ENABLE-REAL-AI.md#6",
    "path": "docs/ENABLE-REAL-AI.md",
    "title": "ENABLE-REAL-AI.md",
    "text": "1. Go to https://vercel.com/coding-krakken-projects/extrasure-project/settings/environment-variables 2. Add a new environment variable: - **Name**: `OPENAI_API_KEY` - **Value**: Your OpenAI API key (starts with `sk-`) - **Environment**: Production, Preview, and Development 3. Optional but recommended: - **Name**: `AI_CHAT_MODEL` - **Value**: `gpt-4o-mini` - **Environment**: All 4. Optional but recommended: - **Name**: `AI_TRIAGE_MODEL` - **Value**: `gpt-4o-mini` - **Environment**: All 5. Redeploy your application"
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#1",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "This document describes the local payment preference model that complements Stripe as the payment processor source of truth. The goal is to support ACH-first checkout UX, customer autopay intent, and admin adoption analytics while keeping existing payment flows backward compatible."
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#2",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "- preferredPaymentMethod: enum card | ach | none (default none) - autopayEnabled: boolean (default false) - autopayMethodType: enum card | ach | none (default none) - achDiscountEligible: boolean (default true)"
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#3",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "- id - customerId - stripePaymentMethodId (unique) - type (card | ach) - brand - last4 - isDefault - createdAt - updatedAt"
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#4",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "- syncSavedPaymentMethodsFromStripe(stripeCustomerId) - syncAllSavedPaymentMethodsFromStripe() - getCustomerPaymentMethods(customerId) - getDefaultPaymentMethod(customerId)"
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#5",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "- setPreferredPaymentMethod(customerId, type) - enableAutopay(customerId, methodType) - disableAutopay(customerId) - updateCustomerPaymentPreferences(customerId, options)"
  },
  {
    "id": "docs/PAYMENT-PREFERENCES.md#6",
    "path": "docs/PAYMENT-PREFERENCES.md",
    "title": "PAYMENT-PREFERENCES.md",
    "text": "- applyAchDiscountIfEligible(paymentIntentId, customerId, originalAmount) - attachPaymentMethodPreference(paymentIntentId, preferredMethod) - getPaymentElementOptionsForAch(customerId, isRecurring)"
  },
  {
    "id": "prisma/schema.postgresql.prisma#1",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "enum AutomationEventType { lead_alert appointment_reminder invoice_reminder failed_payment_retry review_request seasonal_reservice triage_high_urgency triage_unresolved_high_risk triage_follow_up_due }"
  },
  {
    "id": "prisma/schema.postgresql.prisma#2",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "model Customer { id String @id name String phone String email String city String addressLine1 String? addressLine2 String? postalCode String? stateProvince String? activePlan ActivePlan lifecycle Lifecycle lastServiceDate DateTime stripeCustomerId String? @unique stripeSubscriptionId String? stripeSubscriptionStatus String? preferredPaymentMethod PaymentPreferenceMethod @default(none) autopayEnabled Boolean @default(false) autopayMethodType PaymentPreferenceMethod @default(none) achDiscountEligible Boolean @default(true) triageAssessments TriageAssessment[] }"
  },
  {
    "id": "prisma/schema.postgresql.prisma#3",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "model SavedPaymentMethod { id String @id customerId String stripePaymentMethodId String @unique type PaymentMethod brand String last4 String isDefault Boolean @default(false) createdAt DateTime @default(now()) updatedAt DateTime @updatedAt"
  },
  {
    "id": "prisma/schema.postgresql.prisma#4",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "model ServiceCatalogItem { id String @id name String description String serviceType String kind ServiceCatalogKind @default(one_time) billingCycle BillingCycle amount Int active Boolean @default(true) stripeProductId String? stripePriceId String? sortOrder Int @default(0) durationMinutes Int @default(90) bookingLookaheadDays Int @default(30) createdAt DateTime @default(now()) updatedAt DateTime @updatedAt }"
  },
  {
    "id": "prisma/schema.postgresql.prisma#5",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "model ServiceBooking { id String @id customerId String serviceCatalogItemId String invoiceId String? idempotencyKey String? @unique contactName String contactEmail String contactPhone String preferredDate DateTime preferredWindow String addressLine1 String addressLine2 String? city String postalCode String? stateProvince String? notes String? status ServiceBookingStatus @default(checkout_pending) scheduledAt DateTime? technicianId String? stripeCheckoutSessionId String? stripeSubscriptionId String? paidAt DateTime? createdAt DateTime @default(now()) updatedAt DateTime @updatedAt triageAssessments TriageAssessment[] }"
  },
  {
    "id": "prisma/schema.postgresql.prisma#6",
    "path": "prisma/schema.postgresql.prisma",
    "title": "schema.postgresql.prisma",
    "text": "model TriageAssessment { id String @id customerId String serviceBookingId String? source String @default(\"triage_engine_v1\") likelyPest String confidence Float severity TriageSeverity urgency TriageUrgency recommendedService String estimatedPriceRange String recommendedTimeline String safetyConsiderations String[] followUpQuestions String[] riskFactors String[] conversionLikelihood TriageConversionLikelihood guidedAnswersJson String? photosJson String? needsFollowUp Boolean @default(false) resolvedAt DateTime? createdAt DateTime @default(now()) updatedAt DateTime @updatedAt customer Customer @relation(fields: [customerId], references: [id], onDelete: Cascade) serviceBooking ServiceBooking? @relation(fields: [serviceBookingId], references: [id], onDelete: SetNull) overrides AssessmentOverride[]"
  },
  {
    "id": "scripts/prisma-prepare.mjs#1",
    "path": "scripts/prisma-prepare.mjs",
    "title": "prisma-prepare.mjs",
    "text": "function resolveSchemaPath() { const databaseUrl = resolveDatabaseUrl(); const isVercelBuild = process.env.VERCEL === \"1\";"
  },
  {
    "id": "scripts/prisma-prepare.mjs#2",
    "path": "scripts/prisma-prepare.mjs",
    "title": "prisma-prepare.mjs",
    "text": "const schemaPath = resolveSchemaPath(); const isVercelBuild = process.env.VERCEL === \"1\"; const shouldPushSchema = process.env.PRISMA_DB_PUSH_ON_BUILD === \"true\" || (isVercelBuild && process.env.DISABLE_PRISMA_DB_PUSH_ON_BUILD !== \"true\");"
  },
  {
    "id": "scripts/prisma-prepare.mjs#3",
    "path": "scripts/prisma-prepare.mjs",
    "title": "prisma-prepare.mjs",
    "text": "if (shouldPushSchema) { console.log(\"[prisma] Applying schema with prisma db push\"); run(`npx prisma db push --skip-generate --accept-data-loss --schema ${schemaPath}`); }"
  },
  {
    "id": "scripts/prisma-prepare.mjs#4",
    "path": "scripts/prisma-prepare.mjs",
    "title": "prisma-prepare.mjs",
    "text": "if (isVercelBuild && process.env.PRISMA_RUN_PRODUCTION_SEED_ON_BUILD === \"true\") { console.log(\"[prisma] PRISMA_RUN_PRODUCTION_SEED_ON_BUILD=true, running production seed\"); run(\"npx tsx prisma/seed-production.ts\"); }"
  },
  {
    "id": "src/lib/admin-auth.ts#1",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "import { createHmac, timingSafeEqual } from \"node:crypto\"; import { cookies } from \"next/headers\"; import { redirect } from \"next/navigation\"; import type { Role } from \"@/lib/admin-data\"; import { prisma } from \"@/lib/prisma\";"
  },
  {
    "id": "src/lib/admin-auth.ts#2",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "function encodeSession(session: AdminSession) { const payload = JSON.stringify(session); const signature = signPayload(payload); const token = `${payload}.${signature}`;"
  },
  {
    "id": "src/lib/admin-auth.ts#3",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "function decodeSession(token: string): AdminSession | null { try { const decoded = Buffer.from(token, \"base64url\").toString(\"utf8\"); const splitIndex = decoded.lastIndexOf(\".\");"
  },
  {
    "id": "src/lib/admin-auth.ts#4",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "const payload = decoded.slice(0, splitIndex); const signature = decoded.slice(splitIndex + 1); const expectedSignature = signPayload(payload);"
  },
  {
    "id": "src/lib/admin-auth.ts#5",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "function parseRole(input: string | undefined): Role { if (input === \"dispatch\" || input === \"technician\" || input === \"accountant\") { return input; }"
  },
  {
    "id": "src/lib/admin-auth.ts#6",
    "path": "src/lib/admin-auth.ts",
    "title": "admin-auth.ts",
    "text": "export async function createAdminSession(name: string, roleInput?: string) { const role = parseRole(roleInput); const exp = Date.now() + SESSION_TTL_SECONDS * 1000;"
  },
  {
    "id": "src/lib/admin-page-data.ts#1",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "export async function loadAdminPageData(): Promise<AdminPageDataResult> { try { return { state: await getAdminState(), dataError: null, }; } catch (error) { if (error instanceof AdminDataUnavailableError) { return { state: null, dataError: error.message, }; }"
  },
  {
    "id": "src/lib/admin-page-data.ts#2",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "export type AchAdoptionMetrics = { totalCustomers: number; achEnabledCustomers: number; autopayCustomers: number; achDiscountUsageCount: number; achMethodShareByBillingCycle: { monthly: number; quarterly: number; annual: number; }; };"
  },
  {
    "id": "src/lib/admin-page-data.ts#3",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "export type PaymentMethodDistribution = { card: { count: number; percentage: number; }; ach: { count: number; percentage: number; }; };"
  },
  {
    "id": "src/lib/admin-page-data.ts#4",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "export async function getAchAdoptionMetrics(initialState?: AdminState | null): Promise<AchAdoptionMetrics> { const state = initialState ?? (await loadAdminPageData()).state;"
  },
  {
    "id": "src/lib/admin-page-data.ts#5",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "if (!state) { return { totalCustomers: 0, achEnabledCustomers: 0, autopayCustomers: 0, achDiscountUsageCount: 0, achMethodShareByBillingCycle: { monthly: 0, quarterly: 0, annual: 0, }, }; }"
  },
  {
    "id": "src/lib/admin-page-data.ts#6",
    "path": "src/lib/admin-page-data.ts",
    "title": "admin-page-data.ts",
    "text": "const totalCustomers = state.customers.length; const achEnabledCustomers = state.customers.filter((customer) => customer.preferredPaymentMethod === \"ach\").length; const autopayCustomers = state.customers.filter((customer) => customer.autopayEnabled).length;"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#1",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "import { prisma } from \"@/lib/prisma\"; import { getTriageHumanReviewConfidenceThreshold, isTriageEnabled } from \"@/lib/triage-runtime\";"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#2",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "export type OperationalState = { triageKillSwitchDisabled: boolean; triageHumanReviewThreshold: number; updatedAt: Date; updatedBy: string | null; };"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#3",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "export async function getOperationalSettings(): Promise<OperationalState> { // Use cache if still valid if (settingsCache && cacheTtl > Date.now() - CACHE_DURATION_MS) { return settingsCache; }"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#4",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "if (settings) { settingsCache = { triageKillSwitchDisabled: settings.triageKillSwitchDisabled, triageHumanReviewThreshold: settings.triageHumanReviewThreshold, updatedAt: settings.updatedAt, updatedBy: settings.updatedBy, }; cacheTtl = Date.now(); return settingsCache; } } catch (error) { console.error(\"Failed to fetch operational settings:\", error); }"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#5",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "// Fallback to environment variables return { triageKillSwitchDisabled: !isTriageEnabled(), triageHumanReviewThreshold: getTriageHumanReviewConfidenceThreshold(), updatedAt: new Date(), updatedBy: null, }; }"
  },
  {
    "id": "src/lib/admin-operational-settings.ts#6",
    "path": "src/lib/admin-operational-settings.ts",
    "title": "admin-operational-settings.ts",
    "text": "export async function setTriageKillSwitch(disabled: boolean, actor: string): Promise<OperationalState> { try { const settings = await prisma.operationalSettings.upsert({ where: { id: \"singleton\" }, create: { id: \"singleton\", triageKillSwitchDisabled: disabled, triageHumanReviewThreshold: getTriageHumanReviewConfidenceThreshold(), updatedBy: actor, }, update: { triageKillSwitchDisabled: disabled, updatedBy: actor, updatedAt: new Date(), }, });"
  },
  {
    "id": "src/lib/admin-manual-store.ts#1",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "import { prisma } from \"@/lib/prisma\"; import { decryptManualSecret, encryptManualSecret } from \"@/lib/admin-manual-crypto\";"
  },
  {
    "id": "src/lib/admin-manual-store.ts#2",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "export type AdminManualSecretListItem = { id: string; title: string; platform: string; category: ManualCategory; portalUrl: string | null; username: string | null; notes: string | null; isActive: boolean; lastRotatedAt: Date | null; updatedAt: Date; };"
  },
  {
    "id": "src/lib/admin-manual-store.ts#3",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "export type UpsertManualSecretInput = { title: string; platform: string; category: string; portalUrl?: string; username?: string; notes?: string; secretValue?: string; isActive?: boolean; };"
  },
  {
    "id": "src/lib/admin-manual-store.ts#4",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "function normalizeOptional(input?: string) { const value = (input ?? \"\").trim(); return value.length > 0 ? value : null; }"
  },
  {
    "id": "src/lib/admin-manual-store.ts#5",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "function toListItem( item: Awaited<ReturnType<typeof prisma.adminManualSecret.findFirstOrThrow>>, ): AdminManualSecretListItem { return { id: item.id, title: item.title, platform: item.platform, category: item.category as ManualCategory, portalUrl: item.portalUrl, username: item.username, notes: item.notes, isActive: item.isActive, lastRotatedAt: item.lastRotatedAt, updatedAt: item.updatedAt, }; }"
  },
  {
    "id": "src/lib/admin-manual-store.ts#6",
    "path": "src/lib/admin-manual-store.ts",
    "title": "admin-manual-store.ts",
    "text": "function getValidatedInput(input: UpsertManualSecretInput) { const title = input.title.trim(); const platform = input.platform.trim();"
  },
  {
    "id": "src/lib/audit-log.ts#1",
    "path": "src/lib/audit-log.ts",
    "title": "audit-log.ts",
    "text": "export type AuditAction = | \"chatbot_operation_requested\" | \"chatbot_operation_denied\" | \"chatbot_operation_confirmed\" | \"chatbot_operation_executed\" | \"customer_created\" | \"customer_updated\" | \"customer_deleted\" | \"job_created\" | \"job_updated\" | \"job_deleted\" | \"invoice_created\" | \"invoice_updated\" | \"invoice_deleted\" | \"estimate_created\" | \"estimate_updated\" | \"estimate_deleted\" | \"estimate_approved\" | \"estimate_declined\" | \"estimate_converted_to_job\" | \"estimate_converted_to_invoice\" | \"inventory_created\" | \"inventory_updated\" | \"inventory_deleted\" | \"inventory_adjusted\" | \"automation_created\" | \"automation_updated\" | \"automation_deleted\" | \"automation_status_changed\" | \"admin_user_created\" | \"admin_user_updated\" | \"admin_user_deleted\" | \"admin_user_2fa_toggled\" | \"technician_created\" | \"technician_updated\" | \"technician_deleted\" | \"technician_deduplicated\" | \"technician_status_changed\" | \"payment_refunded\" | \"payment_retried\" | \"service_plan_created\" | \"service_plan_updated\" | \"ser"
  },
  {
    "id": "src/lib/audit-log.ts#2",
    "path": "src/lib/audit-log.ts",
    "title": "audit-log.ts",
    "text": "export async function recordAuditEvent({ actor, role, action, entity, entityId, before, after, }: { actor: string; role: string; action: AuditAction; entity: string; entityId: string; before?: Record<string, unknown> | null; after?: Record<string, unknown> | null; }) { try { await prisma.auditEvent.create({ data: { id: `audit_${Date.now()}`, actor, role, action, entity, entityId, before: before ? JSON.stringify(before) : null, after: after ? JSON.stringify(after) : null, }, }); } catch (error) { console.error(\"Failed to record audit event:\", error); } }"
  },
  {
    "id": "src/lib/audit-log.ts#3",
    "path": "src/lib/audit-log.ts",
    "title": "audit-log.ts",
    "text": "export async function getAuditEvents( filters?: { entity?: string; action?: string; actor?: string; fromDate?: Date; toDate?: Date; }, limit?: number, ) { // eslint-disable-next-line @typescript-eslint/no-explicit-any const where: any = {};"
  },
  {
    "id": "src/lib/audit-log.ts#4",
    "path": "src/lib/audit-log.ts",
    "title": "audit-log.ts",
    "text": "export function parseAuditSnapshot(json: string | null) { try { return json ? JSON.parse(json) : null; } catch { return null; } }"
  },
  {
    "id": "src/lib/payment-preferences.ts#1",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "import { randomUUID } from \"node:crypto\"; import { PaymentPreferenceMethod, PaymentMethod } from \"@prisma/client\"; import { prisma } from \"@/lib/prisma\"; import { getStripe } from \"@/lib/stripe\"; import type { AchDiscountSummary } from \"@/types/payment-preferences\";"
  },
  {
    "id": "src/lib/payment-preferences.ts#2",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "function mapPaymentMethodType(method: { type: string }) { return method.type === \"us_bank_account\" ? PaymentMethod.ach : PaymentMethod.card; }"
  },
  {
    "id": "src/lib/payment-preferences.ts#3",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "function mapPaymentMethodBrand(method: { type: string; card?: { brand?: string | null } | null; }) { if (method.type === \"us_bank_account\") { return \"bank_account\"; }"
  },
  {
    "id": "src/lib/payment-preferences.ts#4",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "function mapPaymentMethodLast4(method: { type: string; card?: { last4?: string | null } | null; us_bank_account?: { last4?: string | null } | null; }) { if (method.type === \"us_bank_account\") { return method.us_bank_account?.last4 ?? \"0000\"; }"
  },
  {
    "id": "src/lib/payment-preferences.ts#5",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "export async function syncSavedPaymentMethodsFromStripe(stripeCustomerId: string) { const customer = await prisma.customer.findUnique({ where: { stripeCustomerId }, select: { id: true }, });"
  },
  {
    "id": "src/lib/payment-preferences.ts#6",
    "path": "src/lib/payment-preferences.ts",
    "title": "payment-preferences.ts",
    "text": "const stripe = getStripe(); const [cards, banks, stripeCustomer] = await Promise.all([ stripe.paymentMethods.list({ customer: stripeCustomerId, type: \"card\", limit: 100, }), stripe.paymentMethods.list({ customer: stripeCustomerId, type: \"us_bank_account\", limit: 100, }), stripe.customers.retrieve(stripeCustomerId), ]);"
  },
  {
    "id": "src/lib/stripe-billing.ts#1",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "import { randomUUID } from \"node:crypto\"; import { PaymentPreferenceMethod, Prisma } from \"@prisma/client\"; import type { StripePaymentElementOptions } from \"@stripe/stripe-js\"; import type Stripe from \"stripe\"; import { prisma } from \"@/lib/prisma\"; import { createInvoiceAccessToken } from \"@/lib/customer-billing-access\"; import { calculateAchDiscount, isAchDiscountEligible, syncSavedPaymentMethodsFromStripe } from \"@/lib/payment-preferences\"; import { getBaseUrl, stripe } from \"@/lib/stripe\"; import type { AchDiscountSummary, PaymentMethodType } from \"@/types/payment-preferences\";"
  },
  {
    "id": "src/lib/stripe-billing.ts#2",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "export async function applyAchDiscountIfEligible( paymentIntentId: string, customerId: string, originalAmount: number, ) { const eligible = await isAchDiscountEligible(customerId);"
  },
  {
    "id": "src/lib/stripe-billing.ts#3",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "await stripe.paymentIntents.update(paymentIntentId, { amount: toUnitAmount(discount.discountedAmount), metadata: { achDiscountApplied: \"true\", achSavingsAmount: String(discount.savingsAmount), achOriginalAmount: String(discount.originalAmount), }, });"
  },
  {
    "id": "src/lib/stripe-billing.ts#4",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "export async function attachPaymentMethodPreference( paymentIntentId: string, preferredMethod: PaymentMethodType, ) { await stripe.paymentIntents.update(paymentIntentId, { metadata: { preferredPaymentMethod: preferredMethod, }, }); }"
  },
  {
    "id": "src/lib/stripe-billing.ts#5",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "export async function getPaymentElementOptionsForAch( customerId: string, isRecurring: boolean, ): Promise<StripePaymentElementOptions> { const customer = await prisma.customer.findUnique({ where: { id: customerId }, select: { preferredPaymentMethod: true, achDiscountEligible: true, }, });"
  },
  {
    "id": "src/lib/stripe-billing.ts#6",
    "path": "src/lib/stripe-billing.ts",
    "title": "stripe-billing.ts",
    "text": "const preferredMethod = customer?.preferredPaymentMethod ?? \"none\"; const achPreferred = preferredMethod === \"ach\"; const achEligible = customer?.achDiscountEligible ?? false;"
  },
  {
    "id": "src/app/admin/manual/page.tsx#1",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "import { AdminShell } from \"@/components/admin/admin-shell\"; import { AdminManualAssistant } from \"@/components/admin/admin-manual-assistant\"; import { AdminManualDiagrams } from \"@/components/admin/admin-manual-diagrams\"; import { ManualGlossaryIndex } from \"@/components/admin/manual/manual-glossary-index\"; import { ManualSectionFrame } from \"@/components/admin/manual/manual-section-frame\"; import { ManualTopControls } from \"@/components/admin/manual/manual-top-controls\"; import { ManualPlatformOperations } from \"@/components/admin/manual/manual-platform-operations\"; import { ManualRoleWalkthroughs } from \"@/components/admin/manual/manual-role-walkthroughs\"; import { ManualSecretsByCategoryClient, PlatformSection } from \"@/components/admin/manual/manual-types\"; import { createManualSecretAction, deleteManualSecretAction, updateManualSecretAction, } from \"@/app/admin/manual/actions\"; import { getAdminSession } from \"@/lib/admin-auth\"; import { getManualCategories, listManualSecretsByCa"
  },
  {
    "id": "src/app/admin/manual/page.tsx#2",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "type DashboardModuleGuide = { title: string; href: string; whoUsesIt: string; whatItControls: string; commonTasks: string[]; mistakesToAvoid: string[]; };"
  },
  {
    "id": "src/app/admin/manual/page.tsx#3",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "type RoleWalkthrough = { role: string; mission: string; firstFiveClicks: string[]; dailyWorkflow: string[]; emergencyPriority: string[]; };"
  },
  {
    "id": "src/app/admin/manual/page.tsx#4",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "const platformSections: PlatformSection[] = [ { id: \"vercel\", category: \"vercel\", title: \"Vercel Hosting and Deployments\", purpose: \"Vercel hosts this website and publishes each new deployment.\", plainEnglish: \"Think of Vercel as the company that keeps your website running online 24/7. It handles publishing updates and gives logs when something fails.\", whyItExists: \"Without Vercel, visitors cannot reach the website and staff cannot access live API routes. It is the top-level runtime for your production app.\", links: [ { label: \"Vercel Dashboard\", href: \"https://vercel.com/dashboard\" }, { label: \"Project Settings\", href: \"https://vercel.com/dashboard\" }, { label: \"Vercel Documentation\", href: \"https://vercel.com/docs\" }, ], setupChecklist: [ \"Confirm the correct project is connected to the GitHub repository main branch.\", \"Verify production and preview environment variables are present and current.\", \"Confirm domain settings point to the expected production deployment.\", \"Validate buil"
  },
  {
    "id": "src/app/admin/manual/page.tsx#5",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "const dashboardModules: DashboardModuleGuide[] = [ { title: \"Overview\", href: \"/admin\", whoUsesIt: \"Owner, dispatch lead\", whatItControls: \"Business KPIs, current workload, and top-level operational health.\", commonTasks: [ \"Start every morning by checking this page for anomalies.\", \"Review failed payments and unresolved priority tasks.\", \"Use as launch point into other modules.\", ], mistakesToAvoid: [ \"Do not assume green KPIs mean payments webhooks are healthy.\", \"Do not skip reviewing failed items even when totals look normal.\", ], }, { title: \"CRM\", href: \"/admin/customers\", whoUsesIt: \"Dispatch, owner, accounting\", whatItControls: \"Customer records, lifecycle status, and contact details.\", commonTasks: [ \"Search and update customer contact information.\", \"Review lifecycle state before scheduling or invoicing.\", \"Validate payment preferences for billing operations.\", ], mistakesToAvoid: [ \"Do not create duplicate customers when updating existing records.\", \"Do not overwrite phone a"
  },
  {
    "id": "src/app/admin/manual/page.tsx#6",
    "path": "src/app/admin/manual/page.tsx",
    "title": "page.tsx",
    "text": "const incidentGuides: IncidentGuide[] = [ { title: \"Website is down\", symptom: \"Visitors cannot load the site or receive server errors.\", firstResponse: [ \"Open Vercel dashboard and check latest production deployment status.\", \"If latest deployment failed health checks, rollback to previous successful deployment.\", \"Check runtime logs for first fatal error and document timestamp.\", ], escalation: \"Escalate to developer after rollback and log capture if outage exceeds 15 minutes.\", }, { title: \"Payments are not updating\", symptom: \"Invoices remain open after customer pays.\", firstResponse: [ \"Check Stripe webhook deliveries for failures.\", \"Verify STRIPE_WEBHOOK_SECRET and endpoint URL in production settings.\", \"Confirm payment exists in Stripe dashboard and compare event timestamps.\", ], escalation: \"Escalate if webhook replay does not reconcile within 10 minutes.\", }, { title: \"Admin cannot sign in\", symptom: \"Owner login or OAuth flow fails or loops.\", firstResponse: [ \"Validate admi"
  },
  {
    "id": "src/app/admin/payments/page.tsx#1",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "import { AdminShell } from \"@/components/admin/admin-shell\"; import { AdminDataNotice } from \"@/components/admin/admin-data-notice\"; import { CreateStripeInvoiceDraftButton } from \"@/components/admin/create-stripe-invoice-draft-button\"; import { collectInvoiceAction, openBillingPortalAction, refundPaymentAction, } from \"@/app/admin/payments/actions\"; import { GeneratePaymentLinkButton } from \"@/components/admin/generate-payment-link-button\"; import { FinalizeStripeInvoiceButton } from \"@/components/admin/finalize-stripe-invoice-button\"; import { OpenStripeInvoiceLinkButton } from \"@/components/admin/open-stripe-invoice-link-button\"; import { ReconcileInvoiceButton } from \"@/components/admin/reconcile-invoice-button\"; import { ReplayWebhookButton } from \"@/components/admin/replay-webhook-button\"; import { StripeInvoicePdfButton } from \"@/components/admin/stripe-invoice-pdf-button\"; import { SubscriptionLifecycleButton } from \"@/components/admin/subscription-lifecycle-button\"; import { l"
  },
  {
    "id": "src/app/admin/payments/page.tsx#2",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "export default async function AdminPaymentsPage({ searchParams }: PageProps) { const { state, dataError } = await loadAdminPageData(); const params = searchParams ? await searchParams : undefined; const stripeState = params?.stripe;"
  },
  {
    "id": "src/app/admin/payments/page.tsx#3",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "if (!state) { return ( <AdminShell title=\"Payments, Dunning, and Refunds\" subtitle=\"Track card and ACH outcomes, monitor Stripe-managed recovery, and maintain refund controls for billing integrity.\" > {stripeState ? ( <section className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-4 text-sm text-[#33453a]\"> {stripeState === \"success\" ? \"Stripe checkout completed. Billing status will finalize after verified webhook processing.\" : stripeState === \"portal_return\" ? \"Returned from the Stripe billing portal.\" : \"Stripe checkout was canceled before completion.\"} </section> ) : null} <AdminDataNotice message={dataError} /> </AdminShell> ); }"
  },
  {
    "id": "src/app/admin/payments/page.tsx#4",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "const collectionTotal = state.payments .filter((payment) => payment.status === \"succeeded\") .reduce((total, payment) => total + payment.amount, 0); const failedTotal = state.payments .filter((payment) => payment.status === \"failed\") .reduce((total, payment) => total + payment.amount, 0);"
  },
  {
    "id": "src/app/admin/payments/page.tsx#5",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "return ( <AdminShell title=\"Payments, Dunning, and Refunds\" subtitle=\"Track card and ACH outcomes, monitor Stripe-managed recovery, and maintain refund controls for billing integrity.\" > {stripeState ? ( <section className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-4 text-sm text-[#33453a]\"> {stripeState === \"success\" ? \"Stripe checkout completed. Billing status will finalize after verified webhook processing.\" : stripeState === \"portal_return\" ? \"Returned from the Stripe billing portal.\" : \"Stripe checkout was canceled before completion.\"} </section> ) : null}"
  },
  {
    "id": "src/app/admin/payments/page.tsx#6",
    "path": "src/app/admin/payments/page.tsx",
    "title": "page.tsx",
    "text": "<div className=\"grid gap-4 sm:grid-cols-2\"> <article className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-5\"> <p className=\"text-xs uppercase tracking-[0.12em] text-[#5d7267]\">Collected</p> <p className=\"mt-2 text-3xl text-[#153126]\">${collectionTotal}</p> <p className=\"mt-2 text-sm text-[#445349]\">Successful card and ACH transactions in this window.</p> </article> <article className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-5\"> <p className=\"text-xs uppercase tracking-[0.12em] text-[#5d7267]\">Failed Payment Exposure</p> <p className=\"mt-2 text-3xl text-[#153126]\">${failedTotal}</p> <p className=\"mt-2 text-sm text-[#445349]\">Stripe Billing dunning now handles retries and reminders automatically.</p> </article> </div>"
  },
  {
    "id": "src/app/admin/settings/page.tsx#1",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "import { AdminShell } from \"@/components/admin/admin-shell\"; import { AdminDataNotice } from \"@/components/admin/admin-data-notice\"; import { TriageRetentionOpsCard } from \"@/components/admin/triage-retention-ops-card\"; import { TriageRetentionHistoryCard } from \"@/components/admin/triage-retention-history-card\"; import { TriageOperationalControlsCard } from \"@/components/admin/triage-operational-controls-card\"; import { TriageAnomalyDetectionCard } from \"@/components/admin/triage-anomaly-detection-card\"; import { TriageAssessmentOverrideCard } from \"@/components/admin/triage-assessment-override-card\"; import { TriageWebhookNotificationsCard } from \"@/components/admin/triage-webhook-notifications-card\"; import { TriageAssessmentExportCard } from \"@/components/admin/triage-assessment-export-card\"; import { createAdminUserAction, deleteAdminUserAction, toggleAdminUserTwoFactorAction, updateAdminUserAction, updateSchedulingConfigAction, } from \"@/app/admin/settings/actions\"; import { load"
  },
  {
    "id": "src/app/admin/settings/page.tsx#2",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "export default async function AdminSettingsPage() { const { state, dataError } = await loadAdminPageData(); const schedulingConfig = await getSchedulingConfig();"
  },
  {
    "id": "src/app/admin/settings/page.tsx#3",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "return ( <AdminShell title=\"Security and Access Controls\" subtitle=\"Manage role-based permissions, 2FA readiness, and audit controls for owner-level operations.\" > {!state ? <AdminDataNotice message={dataError} /> : ( <> <section className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-5\"> <h2 className=\"text-2xl text-[#1b2f25]\">Create Admin User</h2> <form action={createAdminUserAction} className=\"mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5\"> <input name=\"name\" required placeholder=\"Name\" className=\"rounded-xl border border-[#cbbd9f] bg-[#fffdf6] px-4 py-3 text-sm text-[#1d2f25]\" /> <input name=\"email\" type=\"email\" required placeholder=\"Email\" className=\"rounded-xl border border-[#cbbd9f] bg-[#fffdf6] px-4 py-3 text-sm text-[#1d2f25]\" /> <select name=\"role\" defaultValue=\"owner\" className=\"rounded-xl border border-[#cbbd9f] bg-[#fffdf6] px-4 py-3 text-sm text-[#1d2f25]\"> <option value=\"owner\">Owner</option> <option value=\"dispatch\">Dispatch</option> <option value=\"technician\">Te"
  },
  {
    "id": "src/app/admin/settings/page.tsx#4",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "<section className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-5\"> <h2 className=\"text-2xl text-[#1b2f25]\">Role and MFA Status</h2> <ul className=\"mt-4 space-y-3 text-sm\"> {state.adminUsers.map((user) => { const formId = `admin-user-form-${user.id}`;"
  },
  {
    "id": "src/app/admin/settings/page.tsx#5",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "return ( <li key={user.id} className=\"rounded-xl border border-[#deceb0] bg-[#fff4df] p-3\"> <div className=\"grid gap-2 md:grid-cols-2 xl:grid-cols-5\"> <input form={formId} name=\"name\" defaultValue={user.name} className=\"rounded-lg border border-[#cbbd9f] bg-[#fffdf6] px-3 py-2 text-sm text-[#1d2f25]\" /> <input form={formId} name=\"email\" type=\"email\" defaultValue={user.email ?? \"\"} className=\"rounded-lg border border-[#cbbd9f] bg-[#fffdf6] px-3 py-2 text-sm text-[#1d2f25]\" /> <select form={formId} name=\"role\" defaultValue={user.role} className=\"rounded-lg border border-[#cbbd9f] bg-[#fffdf6] px-3 py-2 text-sm text-[#1d2f25]\"> <option value=\"owner\">Owner</option> <option value=\"dispatch\">Dispatch</option> <option value=\"technician\">Technician</option> <option value=\"accountant\">Accountant</option> </select> <label className=\"flex items-center gap-2 rounded-lg border border-[#cbbd9f] bg-[#fffdf6] px-3 py-2 text-sm text-[#1d2f25]\"> <input form={formId} name=\"twoFactorEnabled\" type=\"checkbo"
  },
  {
    "id": "src/app/admin/settings/page.tsx#6",
    "path": "src/app/admin/settings/page.tsx",
    "title": "page.tsx",
    "text": "<section className=\"rounded-2xl border border-[#d3c7ad] bg-[#fff9eb] p-5\"> <h2 className=\"text-2xl text-[#1b2f25]\">Operational Security Checklist</h2> <ul className=\"mt-3 list-inside list-disc space-y-1 text-sm text-[#445349]\"> <li>Require 2FA for all owner and accounting roles before enabling live refunds.</li> <li>Maintain immutable audit trails for invoice edits, refunds, and role changes.</li> <li>Review failed authentication attempts weekly and rotate privileged credentials quarterly.</li> <li>Confirm webhook signature validation for payment and accounting integrations.</li> </ul> </section>"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#1",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "import { NextRequest, NextResponse } from \"next/server\"; import { requireAdminApiSession } from \"@/lib/admin-auth\"; import { buildAdminManualKnowledgeContext } from \"@/lib/admin-manual-knowledge\"; import { retrieveAdminManualContext } from \"@/lib/admin-manual-retrieval\"; import { recordAdminManualAssistantResponseMode } from \"@/lib/admin-manual-assistant-analytics\";"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#2",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "type AssistantResponseMode = | \"out-of-scope\" | \"dns-clarifier\" | \"dns-guided\" | \"deploy-clarifier\" | \"deploy-guided\" | \"billing-clarifier\" | \"billing-guided\" | \"auth-clarifier\" | \"auth-guided\" | \"generic-clarifier\" | \"grounded-fallback\" | \"grounded-ai\";"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#3",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "const operationsProfile = { hostingPlatform: \"Vercel\", sourceControl: \"GitHub (main branch deploy workflow)\", paymentsPlatform: \"Stripe webhook-driven reconciliation\", runtimeDatabase: \"Prisma with Postgres in production\", criticalEnvVars: [ \"SITE_URL or NEXT_PUBLIC_SITE_URL\", \"ADMIN_AUTH_SECRET\", \"CUSTOMER_AUTH_SECRET\", \"STRIPE_SECRET_KEY\", \"STRIPE_WEBHOOK_SECRET\", \"OPENAI_API_KEY\", ], };"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#4",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "const inScopeKeywords = [ \"admin\", \"dashboard\", \"deploy\", \"deployment\", \"vercel\", \"github\", \"stripe\", \"openai\", \"oauth\", \"dns\", \"domain\", \"prisma\", \"database\", \"postgres\", \"invoice\", \"payment\", \"webhook\", \"environment\", \"env\", \"code\", \"codebase\", \"api\", \"route\", \"auth\", \"login\", \"incident\", \"rollback\", \"hosting\", \"build\", \"manual\", \"operations\", ];"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#5",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "function classifyScope(message: string): ScopeDecision { const query = message.toLowerCase(); const inScope = inScopeKeywords.some((keyword) => query.includes(keyword));"
  },
  {
    "id": "src/app/api/admin/manual-assistant/route.ts#6",
    "path": "src/app/api/admin/manual-assistant/route.ts",
    "title": "route.ts",
    "text": "function normalizeHistory(history: ManualAssistantMessage[] | undefined) { if (!Array.isArray(history)) { return [] as ManualAssistantMessage[]; }"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#1",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "import { NextRequest, NextResponse } from \"next/server\"; import { requireAdminApiRole, requireAdminApiSession } from \"@/lib/admin-auth\"; import { getAdminState } from \"@/lib/admin-store\"; import { createCustomerPaymentLink, createBillingPortalSession, createInvoiceCheckoutSession, createStripeInvoiceForLocalInvoice, finalizeStripeInvoiceForLocalInvoice, getStripeInvoiceDocumentLinks, replayLatestWebhookForInvoice, replayWebhookEventById, reconcileInvoiceFromStripe, setCustomerSubscriptionLifecycle, refundPaymentById, } from \"@/lib/stripe-billing\";"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#2",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "type PaymentActionPayload = { action?: | \"collect\" | \"portal\" | \"refund\" | \"retry\" | \"link\" | \"reconcile\" | \"replay\" | \"subscription\" | \"invoice_sync\" | \"invoice_finalize\" | \"invoice_pdf\" | \"invoice_links\"; invoiceId?: string; customerId?: string; paymentId?: string; eventId?: string; subscriptionAction?: \"pause\" | \"resume\" | \"cancel\"; };"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#3",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "try { payload = (await request.json()) as PaymentActionPayload; } catch { return NextResponse.json({ error: \"Invalid JSON payload\" }, { status: 400 }); }"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#4",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "if (invoice.status === \"paid\" || invoice.status === \"refunded\") { return NextResponse.json({ error: \"Invoice is not eligible for a payment link\" }, { status: 400 }); }"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#5",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "return NextResponse.json({ ok: true, action: \"invoice_sync\", stripeInvoiceId: stripeInvoice.id, status: stripeInvoice.status, }); }"
  },
  {
    "id": "src/app/api/admin/payments/route.ts#6",
    "path": "src/app/api/admin/payments/route.ts",
    "title": "route.ts",
    "text": "return NextResponse.json({ ok: true, action: \"invoice_finalize\", stripeInvoiceId: stripeInvoice.id, status: stripeInvoice.status, }); }"
  },
  {
    "id": "src/app/api/admin/stripe/webhook/route.ts#1",
    "path": "src/app/api/admin/stripe/webhook/route.ts",
    "title": "route.ts",
    "text": "import { NextRequest, NextResponse } from \"next/server\"; import { handleStripeEvent, recordStripeWebhookEvent } from \"@/lib/stripe-billing\"; import { getStripeWebhookSecret, stripe } from \"@/lib/stripe\";"
  },
  {
    "id": "src/app/api/admin/stripe/webhook/route.ts#2",
    "path": "src/app/api/admin/stripe/webhook/route.ts",
    "title": "route.ts",
    "text": "try { event = stripe.webhooks.constructEvent(payload, signature, getStripeWebhookSecret()); } catch (error) { const message = error instanceof Error ? error.message : \"Invalid Stripe webhook signature\"; return NextResponse.json({ error: message }, { status: 400 }); }"
  },
  {
    "id": "src/app/api/admin/stripe/webhook/route.ts#3",
    "path": "src/app/api/admin/stripe/webhook/route.ts",
    "title": "route.ts",
    "text": "return NextResponse.json({ ok: true, received: true, duplicate: recorded.duplicate, eventId: event.id, eventType: event.type, }); }"
  },
  {
    "id": "src/app/api/auth/start/route.ts#1",
    "path": "src/app/api/auth/start/route.ts",
    "title": "route.ts",
    "text": "import { NextRequest, NextResponse } from \"next/server\"; import { beginOAuth, parseOAuthFlow, parseOAuthProvider, redirectWithOAuthError, setOAuthCookies } from \"@/lib/oauth\";"
  },
  {
    "id": "src/app/api/auth/start/route.ts#2",
    "path": "src/app/api/auth/start/route.ts",
    "title": "route.ts",
    "text": "export async function GET(request: NextRequest) { const provider = parseOAuthProvider(request.nextUrl.searchParams.get(\"provider\")); const flow = parseOAuthFlow(request.nextUrl.searchParams.get(\"flow\"));"
  },
  {
    "id": "src/app/api/auth/start/route.ts#3",
    "path": "src/app/api/auth/start/route.ts",
    "title": "route.ts",
    "text": "try { const { authorizationUrl, stateToken } = beginOAuth(request, provider, flow); const redirectResponse = NextResponse.redirect(authorizationUrl); setOAuthCookies(redirectResponse, stateToken, flow);"
  },
  {
    "id": "src/app/api/auth/start/route.ts#4",
    "path": "src/app/api/auth/start/route.ts",
    "title": "route.ts",
    "text": "return redirectResponse; } catch (error) { console.error(\"[oauth/start] failed\", error); return redirectWithOAuthError(request, flow, \"provider_config\"); } }"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#1",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "import { createContext, useContext, useState, useCallback, useMemo, useEffect, type ReactNode } from \"react\"; import { trackEvent, trackTriageEvent } from \"@/lib/analytics\"; import { isTriageUiEnabled } from \"@/lib/triage-runtime\"; import type { BookingAiHandoff } from \"@/lib/booking-assistant-handoff\";"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#2",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "export type AccountContext = { currentPage?: string; pageSummary?: string; customerName?: string; activePlan?: string; lifecycle?: string; city?: string; lastServiceDate?: string; propertyAddress?: string; };"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#3",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "export type ApiChatResponse = { ok: true; sessionId: string; answer: string; language: \"en\" | \"es\"; confidence: \"low\" | \"medium\" | \"high\"; escalateToHuman: boolean; suggestLeadCapture: boolean; handoff: { callHref: string; smsHref: string; contactPath: string; }; operation?: ChatbotOperationResult; };"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#4",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "export type ChatbotOperationAction = | \"list_appointments\" | \"list_technicians\" | \"get_availability\" | \"schedule_appointment\" | \"reschedule_appointment\" | \"cancel_appointment\" | \"assign_technician\";"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#5",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "export type ChatbotOperationRequest = { action: ChatbotOperationAction; payload?: Record<string, unknown>; confirmationToken?: string; };"
  },
  {
    "id": "src/components/chatbot/chatbot-provider.tsx#6",
    "path": "src/components/chatbot/chatbot-provider.tsx",
    "title": "chatbot-provider.tsx",
    "text": "export type ChatbotOperationResult = { action: ChatbotOperationAction; status: \"success\" | \"error\" | \"requires_confirmation\"; requiresConfirmation: boolean; message: string; result?: Record<string, unknown>; confirmationToken?: string; };"
  }
];
